In [1]:
import numpy as np

In [2]:
one_d_array = np.array([1,2,3,4])

In [3]:
one_d_array

array([1, 2, 3, 4])

In [4]:
two_d_array=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
type(two_d_array)

numpy.ndarray

In [7]:
one_d_array.ndim

1

In [8]:
two_d_array.ndim

2

In [9]:
one_d_array.size

4

In [10]:
one_d_array.shape

(4,)

In [11]:
two_d_array.shape

(3, 3)

In [12]:
one_d_array.dtype

dtype('int32')

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.empty((2,3))

array([[1.81364997e-152, 1.17365077e+214, 1.14567460e+243],
       [1.38334702e+267, 2.42766851e-154, 7.69843740e+218]])

In [16]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
array=np.arange(1,11,2)
array

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [19]:
array=np.arange(1,10)

In [20]:
reshape=np.reshape(array,(3,3))

In [21]:
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
reshape.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# sign value of angle in degrees

In [23]:
sin_90 = np.sin(90)

In [24]:
print("value of sin_90=",sin_90)

value of sin_90= 0.8939966636005579


In [25]:
sin_90 = np.sin(90 * np.pi/180)

In [26]:
print("Sine value of angle 90 in radians = ", sin_90)

Sine value of angle 90 in radians =  1.0


In [27]:
cos_180 = np.cos(180)

In [28]:
print("Cosine value of angle 180 in degree = ", cos_180)

Cosine value of angle 180 in degree =  -0.5984600690578581


In [29]:
cos_180 = np.cos(180 * np.pi/180)

In [30]:
print("Cosine value of angle 180 in radians = ", cos_180)

Cosine value of angle 180 in radians =  -1.0


In [31]:
tan_60 = np.tan(60)

In [32]:
print("Tangent value of angle 60 in degree = ", tan_60)

Tangent value of angle 60 in degree =  0.320040389379563


In [33]:
tan_60 = np.tan(60 * np.pi/180)

In [34]:
print("Tangent value of angle 60 in radians = ", tan_60)

Tangent value of angle 60 in radians =  1.7320508075688767
